# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossfitcenter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crossfitmember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workoutrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
